### ISSUE TITLE
Plugin fails activation on Godot 3.1

### ISSUE THREAD

**Issue by PelegMedia** [vnen/godot-tiled-importer#93]
**Plugin version**
Version 2.2 , Godot 3.1.dev.calinou.5d9109
Downloaded from asset lib

**Issue description**
Plugin fails activation with error on a file

**Steps to reproduce**
1. Create a project.
2. Install plugin from assetlib
3. Activate the plugin

Error: 
 res://addons/vnen.tiled_importer/tiled_map_reader.gd:768 - Parse Error: Too many arguments for 'set_custom_properties()' call. Expected at most 2.
 modules/gdscript/gdscript.cpp:587 - Method/Function Failed, returning: ERR_PARSE_ERROR
 res://addons/vnen.tiled_importer/tiled_import_plugin.gd:28 - Parse Error: Could not fully preload the script, possible cyclic reference or compilation error.
 modules/gdscript/gdscript.cpp:587 - Method/Function Failed, returning: ERR_PARSE_ERROR
 res://addons/vnen.tiled_importer/vnen.tiled_importer.gd:36 - Parse Error: Could not fully preload the script, possible cyclic reference or compilation error.
 modules/gdscript/gdscript.cpp:587 - Method/Function Failed, returning: ERR_PARSE_ERROR
 res://addons/vnen.tiled_importer/tiled_map_reader.gd:768 - Parse Error: Too many arguments for 'set_custom_properties()' call. Expected at most 2.
 modules/gdscript/gdscript.cpp:587 - Method/Function Failed, returning: ERR_PARSE_ERROR

![image](https://user-images.githubusercontent.com/39774781/44552608-7ef5aa80-a733-11e8-8c6d-fdf9d54f6357.png)

**Comment by shinaka** [comment]
You can get the plugin to load by making the following changes to tiled_map_reader.gd:
    (773) set_custom_properties(result, ts)
    (851) print_error("Error parsing JSON: " + content.error_string)
    (876) print_error("Error parsing JSON: " + content.error_string)

----

Then restart the editor and the plugin will Activate.

Unfortunately, the plugin will fail at importing tileset/map changes with the following error:

    Resource was not pre cached for the resource section, bug?
    scene\resources\texture.cpp:186 - Condition ' p_image.is_null() ' is true.

**Comment by vnen** [comment]
Eventually I'll make the port to work on 3.1. I usually don't work this for alpha builds because APIs are still in flux (and I'm not currently using this plugin in a project).

Anyone is welcome to propose a PR, just make sure it still works on 3.0.x.

**Comment by shinaka** [comment]
I got it all working and tested in 3.0.6 and 3.1. Submitted the PR!

**Comment by PelegMedia** [comment]
Thank you.
I will also test on 3.1

**Comment by Rawra** [comment]
Was this ever updated to work with Godot 3.1? I still experience this issue.

**Comment by Rawra** [comment]
> Was this ever updated to work with Godot 3.1? I still experience this issue.

Oh, no it seems to work. However, the files on Godot's Asset Library isn't updated.

**Comment by dyerw** [comment]
Ran into this issue using the install from AssetLibrary. Will attempt to install from Github.
