### ISSUE TITLE
Error: Base Type is not Editor Plugin

### ISSUE THREAD

**Issue by Aaron-Fleisher** [vnen/godot-tiled-importer#102]
**Plugin version**
2.2

**Issue description**
![image](https://user-images.githubusercontent.com/43447253/48462207-2b23bc00-e78c-11e8-8608-b41ace0fa533.png)

**Steps to reproduce**
 - Compile latest godot-master
 - Try to activate addon in Plugins tab

**Comment by rosshadden** [comment]
I have the same issue. It might be a Godot issue, because the script it's referring to is definitely extending `EditorPlugin`.

**Comment by rosshadden** [comment]
Does anyone have a workaround for this? @vnen maybe? I can't use the plugin at all anymore because I can't enable it. If I knew which version of Godot it broke it I would rollback, but if nobody knows it might take a git bisect and many coffee breaks to pass the compilation time.

**Comment by Aaron-Fleisher** [comment]
@rosshadden I believe it around 3-4 weeks after 3.0.6 >_< Not entirely sure though, but it was working a bit after 3.0.6 (I was compiling then)

**Comment by vnen** [comment]
Which Godot version are you using? It's working fine on 3.0.6 for me.

Also, check if there are any messages in the console. This is likely a regression if you are not using stable Godot.

**Comment by Aaron-Fleisher** [comment]
@vnen Good question.. sorry for not posting the console messages.

```
SCRIPT ERROR: GDScript::reload: Parse Error: Could not fully preload the script, possible cyclic reference or compilation error.
          At: res://addons/vnen.tiled_importer/vnen.tiled_importer.gd:36
ERROR: GDScript::reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules\gdscript\gdscript.cpp:571
```

Godot version was just a compiled godot on November 13th.
I also found https://github.com/godotengine/godot/issues/20661

**Comment by rosshadden** [comment]
I did a bisect, which took about as long as expected.

```

**Comment by rosshadden** [comment]
I did a bisect, which took about as long as expected.

```
7f6f9abb2ffd43d81272fffff22896becdb7bd48 is the first bad commit
commit 7f6f9abb2ffd43d81272fffff22896becdb7bd48
Author: George Marques <george@gmarqu.es>
Date:   Sun Nov 11 01:42:20 2018 -0200

    Make enum values not be script constants if enum is named

    Anonymous enums still creates script constants.

    Also add a check to see if name used for enum is already defined.

:040000 040000 7ac64e1984f710b0b0c015e2239df3cb82f2df5d 981670918f06c26b63ab1fd2d01fb44d1c11ceca M      modules
```
