### ISSUE TITLE
Map isn't working in 3.1 stable

### ISSUE THREAD

**Issue by flashwebdeveloper** [vnen/godot-tiled-importer#109]
Hi! I have a map in .tmx file but when I create a inherited scene from it there is nothing there. The layers (name only are present) but there are single tiles only not the map. My godot version is 3.1 stable
![Screenshot from 2019-03-28 21-34-09](https://user-images.githubusercontent.com/30574169/55173253-5fc76b80-51a1-11e9-934e-8a1f47b21d59.png)
![Screenshot from 2019-03-28 21-34-43](https://user-images.githubusercontent.com/30574169/55173254-5fc76b80-51a1-11e9-8f91-b837f3e67a91.png)

**Comment by RichardSmart81** [comment]
I'm getting this when  I activate the plugin:


 res://addons/vnen.tiled_importer/vnen.tiled_importer.gd:36 - Parse Error: Could not fully preload the script, possible cyclic reference or compilation error. Use 'load()' instead if a cyclic reference is intended.


And I can't open the script in the editor for some reason.

**Comment by vnen** [comment]
I still need to update the AssetLib version. Please use the code from GitHub in the meantime. I ask the plugin version in the issue template for this very reason.

**Comment by drtwisted** [comment]
I have issues opening tileset (*.tsx) with 3.1.
There are lots of error messages, while the engine tries to open it:
```
ERROR: update_texture_list: Condition ' !tileset->tile_get_texture(E->get()).is_valid() ' is true. Continuing..:
    At: editor/plugins/tile_set_editor_plugin.cpp:2892.
```
![error_messages](https://imgur.com/gV6c7QC.png)

Sometimes tileset is opened, but the editor bottom layout gets totally messed up
![tile_set_editor](https://imgur.com/54IYfV9.png)

**Comment by drtwisted** [comment]
Have created a seperate issue #112 for the above comment. Sorry to have posted it here in first place.
